name: testytesterson
favicon: null
layout_spectrum: 0.9604188611265272
typography_spectrum: 0.46051848446950316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2640993914101273
  lightness: 0.8338505080901086
  saturation: 0.3348878372926265
  rhythmicContrast: 0.19953792565502226
purpose: []
